### ISSUE TITLE
QR Decomposition

### ISSUE THREAD

**Issue by mitjap** [inspirit/jsfeat#30]
I can see you're no longer active on this project so I would like to step in a bit and implement a QR alogirthm using [Modified Gram-Schmidt alogithm](http://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process#Numerical_stability). Are you wiling to accept my pull request if you happen to like my code?

**Comment by zavodnyrichard** [comment]
Sorry for opening this almost 5 years old topic, but my question is relavant to this topic. I'm willing to implement custom "QR" like codes (similiar to Snapchat and Messenger ones) and looking for some existing QR code reader. I found this library as I was looking for OpenCV alternatives for Javascript and somebody recommended this one. Has anybody ever did this?
