### ISSUE TITLE
Does the code correctly account for the endianness of the processor

### ISSUE THREAD

**Issue by CarbonMan** [inspirit/jsfeat#48]
Just wondering how portable across hardware the code in this library is. I was reading this article and came across the problem with the endian problem when doing byte manipulations.
https://hacks.mozilla.org/2011/12/faster-canvas-pixel-manipulation-with-typed-arrays/

**Comment by inspirit** [comment]
most of the functions for image processing designed to work with mono (grayscale) images. so the only function that may be affected by endian issue is converting image to grayscale. if u do a blur of the color images or blur of grayscale image it doesn't matter what is the hardware endian
