### ISSUE TITLE
Customising the background image colour of the canny image

### ISSUE THREAD

**Issue by w9914420** [inspirit/jsfeat#56]
Hello

i was wondering if it is at all possible to customise the background colour of the canny demo from black to a colour of ones choosing.

https://inspirit.github.io/jsfeat/sample_canny_edge.html

ideally I would want to have a transparent background if possible and maybe the option to change the colours of the line edges to another colour apart from white.

I would appreciate any advice/help that you can give.

**Comment by inspirit** [comment]
well this has nothing to do with jsfeat. it gives you the black and white pixels so that you can see where is the gradient goes. how do u render it to screen is up to you. so please refer to JavaScript image operations to solve it.
